### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lishan89uc** [Inrixia/Floatplane-Downloader#10]
I keep getting this error
![capture](https://user-images.githubusercontent.com/24217695/43029623-be3be22a-8c3c-11e8-83c1-c441de7ecf9a.PNG)

**Comment by Inrixia** [comment]
Yea this is due to the latest floatplane video not having a thumbnail. A hotfix for this is currently on the discord and will be being pushed into a release soon. If you want to get it head over to the discord here: https://discord.gg/aNTyMME

And overwrite your float.js with the one in the channel.
