### ISSUE TITLE
Carpool Critics coming in as LLt section video

### ISSUE THREAD

**Issue by torodiesel** [Inrixia/Floatplane-Downloader#105]
I have noticed recently that LTT may have changed the labeling on their videos to TJM for carpool critics. Is there a work around for this?
![Capture 2](https://user-images.githubusercontent.com/52382226/143718493-a2879746-d80a-4050-acf6-0014a05ab0d1.PNG)
![Capture](https://user-images.githubusercontent.com/52382226/143718494-66ec26ad-6e01-4833-a8e2-3985c0376014.PNG)

**Comment by Inrixia** [comment]
Re the **[settings wiki for subscriptions](https://github.com/Inrixia/Floatplane-Downloader/blob/master/wiki/settings.md#subscriptions)** you can update and change the channel identifiers or even add your own channels for matching content.

All you would need to do is add TJM as an additional matcher for Carpool Critics and it should be fixed.

If your willing contribute by making the change to the defaults.ts and making a pull request that would be cool (though make sure you do so on the dev branch). Otherwise I will eventually get around to it and you can just change your config for now.

**Comment by Inrixia** [comment]
Should be fixed in https://github.com/Inrixia/Floatplane-Downloader/commit/181fe92cec117f1863f1e29ab48578489b7637da

Please use a dev build and let me know if it is.

**Comment by Inrixia** [comment]
Considering fixed due to inactivity
