### ISSUE TITLE
Version for docker-compose

### ISSUE THREAD

**Issue by torodiesel** [Inrixia/Floatplane-Downloader#114]
Respectfully,

I would like to request for a version with docker-compose in mind. I use it to easily set environment variables and volume variables to easily get this amazing software up and running. Also If I switch to another server with it just a drop in a .yaml file and its up. 

Nothing important just a feature request.

**Comment by Inrixia** [comment]
You should be able to easily use a docker-compose yml file with the existing image. Have you tried that/need some help?

What's missing that needs to be added?

**Comment by torodiesel** [comment]
When building the .yaml file and deploying I am not able to authenticate with and without a token when connecting to floatplane I always get a code 403. Also, There is really no examples of all the environmental variables such as what channels to disable such as carpool critics or floatplane exclusives as I do not watch those.

Authenticating with Plex has the same issue as above on my end. Not sure if others have it as well.

The way I get around this is I download the linux version. I setup the db folder with that. As soon as It shows it downloading videos I stop it and start up docker-compose and it just pulls the config out of the setting.json file.

**Comment by Inrixia** [comment]
Sorry for the delay in replying. Most of the info for docker is on the wiki here https://github.com/Inrixia/Floatplane-Downloader/blob/master/wiki/docker.md

There are only `latest` and `dev` tags, individual versions don't have images on DockerHub. If you wanted them you would need to pull the repo and build the image yourself which is straightforward.

The wiki also includes info on how to use username/password/token though this is really only intended for initial login especially since your 2fa token will change and you need to use it quickly. The best approach is to login once and then have your cookies.json under the `_db` folder persisted.

As for settings, same thing applies its much easier to persist the config file under `_db` than set settings as env args. That said if you want a one click deploy then you can set any setting using env args by replacing dots with underscores, its covered in the docker wiki but if it doesn't make sense I can try explain it more.

Unfortunately if you have 2fa enabled then if you don't persist your `cookies.json` in the `_db` folder you will need to update your token every time you need to login or redeploy. If you do persist your `cookies.json` then you don't need any credentials in the env args.

**Comment by rpungello** [comment]
You can use https://www.composerize.com to convert the docker run command they give you into a `docker-compose.yml` file. You just have to run the setup manually first, but from there on out you can just run `docker-compose up -d` to get the thing running.

**Comment by Inrixia** [comment]
Closing as I believe the last two comments should point users in the right direction. If this is still a issue or someone comes along this having issues please re open this discussion or contact me on discord.
