### ISSUE TITLE
[Feature] Add download-order option to configuration

### ISSUE THREAD

**Issue by AltriusRS** [Inrixia/Floatplane-Downloader#201]
This feature would be a simple string option in the config file, which would allow the use to specify their preferred download order for content. You could have it set to download oldest content first, or newest first (which appears to be the current default). 

At the moment, I cannot see a purpose for this except for making it so that if the downloader has been off for a while, the downloads are populated in the order that they were uploaded, instead of reverse chronologically. Allowing folk to catch up while downloading.

**Comment by Inrixia** [comment]
Due to how the downloader pushes videos into the queue asynchronously to support re-ordering would require fetching all videos, sorting and then queueing.

While doable I don't think the added complexity of having two pipelines to facilitate that is worth it for a feature most people would not use sorry.

But thanks for the suggestion
