### ISSUE TITLE
Feature Request: Video Retention Minimum

### ISSUE THREAD

**Issue by ThomasHineXYZ** [Inrixia/Floatplane-Downloader#205]
The concept is to have an option or setting, either globally or per channel, called "minimumVideosToKeep." 

This setting ensures that a specified number of videos (e.g., 1 or 2) are always retained for each channel. This is particularly useful for channels that do not receive frequent uploads, as it prevents Plex metadata and cover art from being cleared by ensuring there is always at least one "episode" per "show."

This would work in tandem with the "daysToKeep" setting. Uploads could be cleared out after a specified number of days, but only for the episodes after the retention minimum count.

_Originally posted by @ThomasHineXYZ in https://github.com/Inrixia/Floatplane-Downloader/issues/117#issuecomment-2136221987_

**Comment by ThomasHineXYZ** [comment]
Fixes previously closed #117

**Comment by ThomasHineXYZ** [comment]
Having it default to zero should maintain functionality with current set ups.

**Comment by Inrixia** [comment]
I swear there is a plex sitting that allows for deleted items to not actually dissappear n stuff.

Looking over this it shouldn't be that difficult to implement, when I originally considered this I thought it would have been more complicated as I was looking at it as it's own setting seperate from daysToKeep but I get it now.

I'm going to close this since it's quite stale now. But if you still want it please leave a comment and I'll re-open it and implement it.

Apologies for the delay
