### ISSUE TITLE
Feature: Use publish date as file creation and modify date

### ISSUE THREAD

**Issue by DavidSpek** [Inrixia/Floatplane-Downloader#35]
Due to the episode numbering being completely random I chose to disable it as it was doing more harm to the sorting in Plex than good. With the publication date in the file name plex will create season folders for each year. However, if the creation and modification date of the file is edited to the publication date this will fix the issues when downloading a large backlog of videos. With 10,000 set in the settings, all videos on Floatplane from LTT will be downloaded. I used Advanced Renamer (free windows software) to edit the creation and modification dates based on the date in the file name and it has worked fairly well, although it does get stuck when loading the files so patience is needed. 

Having this built into the software would be a really nice feature, as Sonarr and Radarr also do this to avoid new versions showing up as new in Plex.

**Comment by Inrixia** [comment]
Ill look into adding it for the rewrite. Episode numbers only break when you are bulk downloading all videos which is not actually the intended use, especially since floatplane naming for subchannels has changed so sorting for TechLinked/TechQuickie will break fairly quickly and everything will end up just under LTT. I have plans to write a version of this for youtube channels so that you can download the entire backlog though.

**Comment by DavidSpek** [comment]
Wouldn't the youtube version just be youtube-dl with a script to grab the thumbnails and nfo?

**Comment by Inrixia** [comment]
Added in https://github.com/Inrixia/Floatplane-Downloader/commit/8e6ca964e34e7e7ae766eb24a0634c9145eb7a10
Will release with v5

Episode numbering should be much more reliable in v5 too.
