### ISSUE TITLE
When there are 2 videos in the same post, the downloader don't download the two of them

### ISSUE THREAD

**Issue by PauloDanielCarneiro** [Inrixia/Floatplane-Downloader#54]
In the video:
![image](https://user-images.githubusercontent.com/15021651/113652610-7b0bc200-966a-11eb-9565-dc7bad306fe4.png)

There is two video, and the downloader is downloading only the second one.

**Comment by Inrixia** [comment]
The dual videos on the blogpost have been removed as you can see here:
![image](https://user-images.githubusercontent.com/6373693/114644781-4532a180-9d2c-11eb-94cb-f85b1ffeb759.png)

However I am adding support for multiple video attachments with files downloaded being postfixed with -part1 and -part2
From what I'm aware videos like this are for now rare. Though if it becomes more prevalent I may need to revisit this fix to add ffmpeg muxing so as to avoid issues with plex throwing a hissyfit.

**Comment by Inrixia** [comment]
On second thought due to the complexity of adding support for multipart videos without also having to update all the code that handles download recovery, naming, etc I'm going to leave it as is and add support down the line if it crops up again.

**Comment by Fma965** [comment]
As per your discord comment, this is still an issue.

**Comment by Fma965** [comment]
![image](https://user-images.githubusercontent.com/1707290/128904083-d496b133-ca54-4a70-96a7-f246d3f4c671.png)
This appears to becoming more common.

https://www.floatplane.com/post/M6t3xa1BSw

**Comment by Inrixia** [comment]
![image](https://user-images.githubusercontent.com/6373693/140599026-6d7ead69-dbf9-451a-8476-8941454863c4.png)

Added in https://github.com/Inrixia/Floatplane-Downloader/commit/dce7ad0a977f536a1ad4a48401f66d88301b8b04!

Note that this is somewhat slapped in but works perfectly fine. Download resumption is disabled for multi part videos as I am still only tracking one byte count per video. But this is fine due to the infrequency of these videos and if needed in the future would not be hard to add on, though doing so would be a breaking change.
